-- Seed: profs du Cégep de Granby
-- Exécuter dans Supabase SQL Editor
-- created_by est NULL car inséré manuellement (service role bypass RLS)

INSERT INTO profs (name, cegep, dept, courses) VALUES

-- ============ SCIENCES HUMAINES & SCIENCES DE LA NATURE ============
('Laïla Audette',              'Cégep de Granby', 'Sciences humaines',    '{}'),
('Anthoni Barbe',              'Cégep de Granby', 'Sciences humaines',    '{}'),
('Frédérique Beaudoin-Dion',   'Cégep de Granby', 'Sciences humaines',    '{}'),
('Véronique Beaulieu-Audy',    'Cégep de Granby', 'Sciences de la nature','{}'),
('Marc-André Bergeron',        'Cégep de Granby', 'Sciences humaines',    '{}'),
('Mélissa Boisvert',           'Cégep de Granby', 'Sciences de la nature','{}'),
('Mathieu Boivin-Chouinard',   'Cégep de Granby', 'Sciences humaines',    '{}'),
('Nicolas Bolduc',             'Cégep de Granby', 'Sciences humaines',    '{}'),
('Yasser Boulmezaoud',         'Cégep de Granby', 'Sciences humaines',    '{}'),
('Nicholas Bourdon',           'Cégep de Granby', 'Sciences humaines',    '{}'),
('Victor Cameron',             'Cégep de Granby', 'Sciences de la nature','{}'),
('Amélie Castagner',           'Cégep de Granby', 'Sciences humaines',    '{}'),
('Alexandre Cléroux Cuillerier','Cégep de Granby','Sciences de la nature','{}'),
('Mélanie Corriveau',          'Cégep de Granby', 'Sciences humaines',    '{}'),
('Sylvie Croteau',             'Cégep de Granby', 'Sciences de la nature','{}'),
('Joannie Daigneault',         'Cégep de Granby', 'Sciences humaines',    '{}'),
('Isabelle Derome',            'Cégep de Granby', 'Sciences humaines',    '{}'),
('Dominic Duguay',             'Cégep de Granby', 'Sciences de la nature','{}'),
('Mathieu Dumais',             'Cégep de Granby', 'Sciences de la nature','{}'),
('Mireille Falardeau',         'Cégep de Granby', 'Sciences humaines',    '{}'),
('Alexandre Foh-Dion',         'Cégep de Granby', 'Sciences de la nature','{}'),
('Mathieu Fournier',           'Cégep de Granby', 'Sciences humaines',    '{}'),
('Éloïse Giraud',              'Cégep de Granby', 'Sciences humaines',    '{}'),
('Sébastien Godin-Proulx',     'Cégep de Granby', 'Sciences de la nature','{}'),
('Véronique Gosselin',         'Cégep de Granby', 'Sciences humaines',    '{}'),
('Vincent Grégoire',           'Cégep de Granby', 'Sciences de la nature','{}'),
('Jacinthe Hamelin',           'Cégep de Granby', 'Sciences humaines',    '{}'),
('Anne Hurtubise',             'Cégep de Granby', 'Sciences humaines',    '{}'),
('Alexis Lafleur',             'Cégep de Granby', 'Sciences humaines',    '{}'),
('Mathilde Langlois',          'Cégep de Granby', 'Sciences de la nature','{}'),
('Emmanuel Lapierre',          'Cégep de Granby', 'Sciences humaines',    '{}'),
('Lucie Lapointe',             'Cégep de Granby', 'Sciences humaines',    '{}'),
('Louise Leblanc',             'Cégep de Granby', 'Sciences humaines',    '{}'),
('Pierre-Philippe Lefebvre',   'Cégep de Granby', 'Sciences humaines',    '{}'),
('Julien Leissner-Martin',     'Cégep de Granby', 'Sciences de la nature','{}'),
('Valérie Lessard',            'Cégep de Granby', 'Sciences humaines',    '{}'),
('Victor Létourneau',          'Cégep de Granby', 'Sciences de la nature','{}'),
('Armel Cédric Makon',         'Cégep de Granby', 'Sciences humaines',    '{}'),
('Sarah Massicotte-Laforge',   'Cégep de Granby', 'Sciences humaines',    '{}'),
('Pier-Luc Migneault',         'Cégep de Granby', 'Sciences humaines',    '{}'),
('Elyane Montmarquet',         'Cégep de Granby', 'Sciences humaines',    '{}'),
('Julie Moore Gagné',          'Cégep de Granby', 'Sciences de la nature','{}'),
('Geneviève Nault',            'Cégep de Granby', 'Sciences de la nature','{}'),
('Viviane Noiseux',            'Cégep de Granby', 'Sciences de la nature','{}'),
('Virginie Proulx-Tremblay',   'Cégep de Granby', 'Sciences humaines',    '{}'),
('Samuel Provencher-Tardif',   'Cégep de Granby', 'Sciences de la nature','{}'),
('Justine Racicot',            'Cégep de Granby', 'Sciences humaines',    '{}'),
('Sahar Ramazan Ali',          'Cégep de Granby', 'Sciences humaines',    '{}'),
('Jean-François Rivard',       'Cégep de Granby', 'Sciences de la nature','{}'),
('Patrice Roberge',            'Cégep de Granby', 'Sciences de la nature','{}'),
('Matthieu Samson',            'Cégep de Granby', 'Sciences humaines',    '{}'),
('Amélie Sintes',              'Cégep de Granby', 'Sciences humaines',    '{}'),
('Benoit Sirois',              'Cégep de Granby', 'Sciences de la nature','{}'),
('Marisol Tanguay',            'Cégep de Granby', 'Sciences de la nature','{}'),
('Karel Tétreault-Robert',     'Cégep de Granby', 'Sciences humaines',    '{}'),
('François Tougas',            'Cégep de Granby', 'Sciences humaines',    '{}'),
('Chantale Tremblay',          'Cégep de Granby', 'Sciences humaines',    '{}'),
('Guertin Tremblay',           'Cégep de Granby', 'Sciences humaines',    '{}'),
('Marie-Josée Turmel',         'Cégep de Granby', 'Sciences humaines',    '{}'),

-- ============ FRANÇAIS ============
('Simon Benjamin',             'Cégep de Granby', 'Français',             '{}'),
('Amielie Bourbonnais',        'Cégep de Granby', 'Français',             '{}'),
('Marc Boyer',                 'Cégep de Granby', 'Français',             '{}'),
('Julie Caron',                'Cégep de Granby', 'Français',             '{}'),
('Julie Chamberland',          'Cégep de Granby', 'Français',             '{}'),
('François Chaput',            'Cégep de Granby', 'Français',             '{}'),
('Tristan Coutu',              'Cégep de Granby', 'Français',             '{}'),
('Julie Dehin',                'Cégep de Granby', 'Français',             '{}'),
('Daniel Dupré',               'Cégep de Granby', 'Français',             '{}'),
('Joanne Garneau',             'Cégep de Granby', 'Français',             '{}'),
('Sonia Grenon',               'Cégep de Granby', 'Français',             '{}'),
('Judith Haviernick',          'Cégep de Granby', 'Français',             '{}'),
('Marie Hébert',               'Cégep de Granby', 'Français',             '{}'),
('Julie Houle',                'Cégep de Granby', 'Français',             '{}'),
('Vincent Jordan',             'Cégep de Granby', 'Français',             '{}'),
('Mélanie Lajoie',             'Cégep de Granby', 'Français',             '{}'),
('Vincent Landry',             'Cégep de Granby', 'Français',             '{}'),
('Michèle Leblanc',            'Cégep de Granby', 'Français',             '{}'),
('Dominic Marcil',             'Cégep de Granby', 'Français',             '{}'),
('Antonin Marquis',            'Cégep de Granby', 'Français',             '{}'),
('Marie Michaud',              'Cégep de Granby', 'Français',             '{}'),
('Hombeline Passot',           'Cégep de Granby', 'Français',             '{}'),
('David Paulin',               'Cégep de Granby', 'Français',             '{}'),
('Madeleine Poulin',           'Cégep de Granby', 'Français',             '{}'),
('Charles Robert',             'Cégep de Granby', 'Français',             '{}'),
('Annie Rousseau',             'Cégep de Granby', 'Français',             '{}'),
('Ariane Tremblay',            'Cégep de Granby', 'Français',             '{}'),
('Matthieu Verrette',          'Cégep de Granby', 'Français',             '{}'),

-- ============ ANGLAIS ============
('Saeid Bayat',                'Cégep de Granby', 'Anglais',              '{}'),
('Joy Blake',                  'Cégep de Granby', 'Anglais',              '{}'),
('Gabrielle Caron',            'Cégep de Granby', 'Anglais',              '{}'),
('Kawtar Chellaoui',           'Cégep de Granby', 'Anglais',              '{}'),
('Alden Chorush',              'Cégep de Granby', 'Anglais',              '{}'),
('Christopher Conk',           'Cégep de Granby', 'Anglais',              '{}'),
('Michael James',              'Cégep de Granby', 'Anglais',              '{}'),
('Milos Kovacevic',            'Cégep de Granby', 'Anglais',              '{}'),
('Heidi Lajoie',               'Cégep de Granby', 'Anglais',              '{}'),
('Jill Landry',                'Cégep de Granby', 'Anglais',              '{}'),
('Liel Plamondon',             'Cégep de Granby', 'Anglais',              '{}'),
('Sebastien Savoie',           'Cégep de Granby', 'Anglais',              '{}'),
('Aleksandra Serebrenik',      'Cégep de Granby', 'Anglais',              '{}'),
('Tatiana Soto',               'Cégep de Granby', 'Anglais',              '{}'),
('Amélie Tajan-Turcotte',      'Cégep de Granby', 'Anglais',              '{}'),

-- ============ ÉDUCATION PHYSIQUE ============
('Mélanie Blanchard',          'Cégep de Granby', 'Éducation physique',   '{}'),
('Andrew Bourget',             'Cégep de Granby', 'Éducation physique',   '{}'),
('Anne-Marie Brodeur-Fontaine','Cégep de Granby', 'Éducation physique',   '{}'),
('Camille Gravel',             'Cégep de Granby', 'Éducation physique',   '{}'),
('Richard Guilmette',          'Cégep de Granby', 'Éducation physique',   '{}'),
('Arianne Meloche',            'Cégep de Granby', 'Éducation physique',   '{}'),
('Frédéric Parent',            'Cégep de Granby', 'Éducation physique',   '{}'),
('Jean-François Poliquin',     'Cégep de Granby', 'Éducation physique',   '{}'),

-- ============ ÉDUCATION SPÉCIALISÉE ============
('Chrystel Barbarie',          'Cégep de Granby', 'Autre',                '{}'),
('Josée Beaudoin',             'Cégep de Granby', 'Autre',                '{}'),
('Justine Benoit',             'Cégep de Granby', 'Autre',                '{}'),
('Éric Blouin',                'Cégep de Granby', 'Autre',                '{}'),
('Ève-Marie Bouchard',         'Cégep de Granby', 'Autre',                '{}'),
('Marilou Bouchard',           'Cégep de Granby', 'Autre',                '{}'),
('Chantal Bourguignon',        'Cégep de Granby', 'Autre',                '{}'),
('Marie-Christine Brazeau',    'Cégep de Granby', 'Autre',                '{}'),
('Stéphanie Comeau Lamarche',  'Cégep de Granby', 'Autre',                '{}'),
('Stéphane De Senneville',     'Cégep de Granby', 'Autre',                '{}'),
('Karine Demeule',             'Cégep de Granby', 'Autre',                '{}'),
('Camille Dubuc',              'Cégep de Granby', 'Autre',                '{}'),
('Annie Dutil',                'Cégep de Granby', 'Autre',                '{}'),
('Jessica Fontaine',           'Cégep de Granby', 'Autre',                '{}'),
('Annie Gagné',                'Cégep de Granby', 'Autre',                '{}'),
('Isabelle Giard',             'Cégep de Granby', 'Autre',                '{}'),
('Mélissa Grondin',            'Cégep de Granby', 'Autre',                '{}'),
('Daniel Lafontaine',          'Cégep de Granby', 'Autre',                '{}'),
('Catherine Laliberté',        'Cégep de Granby', 'Autre',                '{}'),
('Katherine Latulippe',        'Cégep de Granby', 'Autre',                '{}'),
('RoseMarie Lebeau',           'Cégep de Granby', 'Autre',                '{}'),
('Danielle Leblanc',           'Cégep de Granby', 'Autre',                '{}'),
('Maxime Ledoux',              'Cégep de Granby', 'Autre',                '{}'),
('Audrey Leith',               'Cégep de Granby', 'Autre',                '{}'),
('Marie-Ève Létourneau-Durocher','Cégep de Granby','Autre',               '{}'),
('Caroline Martel',            'Cégep de Granby', 'Autre',                '{}'),
('Lilianne Mathieu',           'Cégep de Granby', 'Autre',                '{}'),
('Myriam Morin',               'Cégep de Granby', 'Autre',                '{}'),
('Mylène Quervel-Chaumette',   'Cégep de Granby', 'Autre',                '{}'),
('Andréanne Simard-Dionne',    'Cégep de Granby', 'Autre',                '{}'),
('Sonia St-Onge',              'Cégep de Granby', 'Autre',                '{}'),
('Frédéric Tessier',           'Cégep de Granby', 'Autre',                '{}'),
('Jessica Trachy',             'Cégep de Granby', 'Autre',                '{}'),
('Marie-Line Vachon',          'Cégep de Granby', 'Autre',                '{}'),
('Sarah Viens',                'Cégep de Granby', 'Autre',                '{}'),

-- ============ TECHNIQUES D'ÉDUCATION À L'ENFANCE ============
('Geneviève Alarie',           'Cégep de Granby', 'Autre',                '{}'),
('Cathy Beaudoin',             'Cégep de Granby', 'Autre',                '{}'),
('Julie Bérubé',               'Cégep de Granby', 'Autre',                '{}'),
('Marie-Josée Cotnoir',        'Cégep de Granby', 'Autre',                '{}'),
('Josiane Croteau',            'Cégep de Granby', 'Autre',                '{}'),
('Stéphanie Forcier',          'Cégep de Granby', 'Autre',                '{}'),
('Julie Leroux',               'Cégep de Granby', 'Autre',                '{}'),
('Hélène Morin',               'Cégep de Granby', 'Autre',                '{}'),
('Eve Normandeau',             'Cégep de Granby', 'Autre',                '{}'),
('Geneviève Perron',           'Cégep de Granby', 'Autre',                '{}'),
('Emmanuelle Prince',          'Cégep de Granby', 'Autre',                '{}'),
('Audrey Simard',              'Cégep de Granby', 'Autre',                '{}'),
('Christine Simard Rousseau',  'Cégep de Granby', 'Autre',                '{}'),
('Marie-Claude St-Jacques',    'Cégep de Granby', 'Autre',                '{}'),

-- ============ PHILOSOPHIE ============
('Simon Blouin',               'Cégep de Granby', 'Philosophie',          '{}'),
('Mélissa Caron',              'Cégep de Granby', 'Philosophie',          '{}'),
('Pier-Luc Champagne',         'Cégep de Granby', 'Philosophie',          '{}'),
('Martin Champagne',           'Cégep de Granby', 'Philosophie',          '{}'),
('Mathieu Charest-Vézina',     'Cégep de Granby', 'Philosophie',          '{}'),
('Philippe Charlebois',        'Cégep de Granby', 'Philosophie',          '{}'),
('Jean-François Dubé',         'Cégep de Granby', 'Philosophie',          '{}'),
('Frédéric Dulac',             'Cégep de Granby', 'Philosophie',          '{}'),
('Grégorie Dupuis-Mc Donald',  'Cégep de Granby', 'Philosophie',          '{}'),
('Cyndelle Gagnon',            'Cégep de Granby', 'Philosophie',          '{}'),
('Bella Jalbert',              'Cégep de Granby', 'Philosophie',          '{}'),
('Amayas Kaci',                'Cégep de Granby', 'Philosophie',          '{}'),
('Jean-François Labonté',      'Cégep de Granby', 'Philosophie',          '{}'),
('Félix Schneller',            'Cégep de Granby', 'Philosophie',          '{}'),
('Anna Katia Tremblay',        'Cégep de Granby', 'Philosophie',          '{}'),
('Joëlle Tremblay',            'Cégep de Granby', 'Philosophie',          '{}'),
('Andréanne Veillette',        'Cégep de Granby', 'Philosophie',          '{}'),
('Philippe Viens',             'Cégep de Granby', 'Philosophie',          '{}')

ON CONFLICT DO NOTHING;
